include: package:flutter_lints/flutter.yaml

# Freezed + JsonSerializable
analyzer:
  errors:
    avoid_print: ignore
    invalid_annotation_target: ignore
    provide_deprecation_message: ignore
  plugins:
    - custom_lint