include: package:flutter_lints/flutter.yaml

# Freezed + JsonSerializable
analyzer:
  errors:
    invalid_annotation_target: ignore
    invalid_use_of_internal_member: ignore
    provide_deprecation_message: ignore
  plugins:
    - custom_lint
formatter:
  page_width: 80