name: On Release

on:
  release: 
    types: [released, prereleased]

jobs:
  analyze:
    name: Analyze
    uses: ./.github/workflows/part_analyze.yml
  build-and-upload:
    name: Build and Upload
    uses: ./.github/workflows/part_build-and-upload.yml
#      with:
#        release-string: ${{ github.event.release.tag_name }}