name: On Release

on:
  release: 
    types: [edited, published]

jobs:
  analyze:
    name: Analyze
    uses: ./.github/workflows/part_analyze.yml
  build-and-upload:
    name: Build and Upload apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: main

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build

      - name: Build profile apk
        run: flutter build apk --profile

      - name: Upload apk to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-profile.apk
          asset_name: lyric_test_${{ github.event.release.tag_name }}.apk
          tag: ${{ github.ref }}
          overwrite: true