name: Dart

on:
  release: 
    types: [released, prereleased]

jobs:
  analyze:
    uses: ./.github/workflows/part_analyze.yml
  build-and-upload:
    uses: ./.github/workflows/part_build-and-upload.yml
#      with:
#        release-string: ${{ github.event.release.tag_name }}