name: Analyze

on:
  workflow_call:

jobs:
  analyze:
    name: "Analyze code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: main
          
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build

      - name: Analyze project source
        run: dart analyze